### PR TITLE
fix(mouse): scale MoveAbsolute coordinates on win32

### LINKED ISSUE #43: [Bug] Mouse::MoveAbsolute different on win32 and x11
**Describe the bug**
The `MoveAbsolute` function parameters are different on win32 and x11. Calling the function on win32 and x11 will yield completely different results.
- On win32, the range is from (0, 0) to (65535, 65535).
- On x11, the range is from (0, 0) to (screen_x, screen_y).

**To Reproduce**
The following snippet will move the cursor to the center of the screen on x11 and top left corner on win32.
```c++
MoveAbsolute(screen_x / 2, screen_y / 2);
```

**Expected behavior**
The cursor should move to the center of the screen on all platforms.

### PR DESCRIPTION
**Pull request by samuelloza**
# Description

For solved this bug
it's necessary to get the **ScreenSize.Width** and **ScreenSize.Height**
This post helped me to resolve the bug

[how-to-calculate-coordinates-to-move-the-mouse-cursor-programmatically](https://stackoverflow.com/questions/21965353/how-to-calculate-coordinates-to-move-the-mouse-cursor-programmatically
)

The scale formula is 
```
x = p.X * 65535 / GetDeviceCaps(GetDC(NULL), HORZRES)
y = p.Y * 65535 / GetDeviceCaps(GetDC(NULL), VERTRES)
```

## Type of change

- [ x ] Bugfix (non-breaking change which fixes an issue)

## How Has This Been Tested?

As you can see, it requires **scaling**, so we are likely to have a small rounding error of +1 or -1.

### CODE REVIEW

File: src/win32/mouse.cpp [hunk 1]
```diff
@@ -14,6 +14,10 @@ Point GetPosition() {
 void MoveAbsolute(int x, int y) {
     // (0, 0) is the top left corner
     // (65535, 65535) is the bottom right corner
+
+    x = x * 65535 / GetDeviceCaps(GetDC(NULL), HORZRES);
```
Comment (sbplat) [inline src/win32/mouse.cpp]: As there is a +1 or -1 rounding error, this should be converted to a float or double and rounded (`std::round`).

Comment (sbplat) [inline src/win32/mouse.cpp]: It looks like `GetDC` and `GetDeviceCaps` will be called every time `MoveAbsolute` is called.

Could the screen size (width and height values) be cached in the `_Context` class?
The `_Context` class is defined in `src/internal.h` and the win32 implementation is in `src/win32/context.cpp`.

**Review by sbplat — CHANGES_REQUESTED** [review]

**Comment by sbplat** [comment]
Thanks for the PR! Caching the values isn't necessary, but it's nice to have.

**Comment by samuelloza** [comment]
> Thanks for the PR! Caching the values isn't necessary, but it's nice to have.

Thanks for your comments, I updated the code.

**Comment by sbplat** [comment]
> > Thanks for the PR! Caching the values isn't necessary, but it's nice to have.
> 
> Thanks for your comments, I updated the code.

I will take a look right now.

File: src/win32/mouse.cpp [hunk 2]
```diff
@@ -16,8 +17,8 @@ void MoveAbsolute(int x, int y) {
     // (65535, 65535) is the bottom right corner
     INPUT input = {0};
     input.type = INPUT_MOUSE;
-    input.mi.dx = x;
-    input.mi.dy = y;
+    input.mi.dx = round(x * 65535 / GetDeviceCaps(GetDC(NULL), HORZRES));
```
Comment (sbplat) [inline src/win32/mouse.cpp]: An integer divided by an integer results in an integer. One possible solution is to use `65535.0` instead of `65535`.

**Review by sbplat — CHANGES_REQUESTED** [review]

**Comment by sbplat** [comment]
Could you also update the move example (`examples/move.cpp`)? It's calling `MoveAbsolute` with `30000` right now and it should be reduced to a smaller number like `200`.

**Review by sbplat — APPROVED** [review]
LGTM, thanks!
